export {default as Brands} from './Brands'
export {default as Cart} from './Cart'
export {default as Details} from './Details'
export {default as Home} from './Home'
export {default as LoginSignup} from './LoginSignup'
export {default as Product} from './Product'
export {default as WishList} from './WishList'